linters:
  disable-all: true
  enable:
    #- goimports
    #- gosec
    #- unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    #- funlen
    - goconst
    - gocritic
    - godot
    - gofmt
    - gosimple
    - govet
    - ineffassign
    - mirror
    - musttag
    - nestif
    - nosprintfhostport
    - predeclared
    - staticcheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - gosec
        - funlen
        - goconst
        - gocritic
        - staticcheck
    - path: 'sql/criteria.go'
      linters:
        - exhaustive
    - path: 'sql/parser.go'
      linters:
        - exhaustive
    - path: 'sql/query.go'
      linters:
        - exhaustive
    - path: 'cmd/sqmail/cmd/output.go'
      text: 'S1000:'
