name: Tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GO_VERSION: "1.23.6"

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest

    outputs:
      src: ${{ steps.filter.outputs.src }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - '**/*.go'
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install go-junit-report
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go install github.com/jstemmer/go-junit-report@latest

      - name: Run Tests
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          go test -v ./... | go-junit-report -set-exit-code > report.xml

      - name: Summarize Test Results
        if: always()
        uses: test-summary/action@v2
        with:
          paths: report.xml
          show: all
